#include <stdio.h>
#include <string.h>
#include "cli.h"
#include "lexer.h"
#include "parser.h"
#include "repl.h"
static int failures=0;
#define CHECK(c) do{if(!(c)){fprintf(stderr,"FALHA %s:%d: %s\n",__FILE__,__LINE__,#c);failures++;}}while(0)
static size_t read_output(FILE *file,char *buffer,size_t capacity){size_t n;rewind(file);n=fread(buffer,1U,capacity-1U,file);buffer[n]='\0';return n;}
static int run_file(const char *path,FILE *out){RuntimeIO io={stdin,out};char *argv[]={"lume",(char *)path};return cli_run(2,argv,io);}
static void test_basic_cache_state_list(void){FILE *out=tmpfile();char buffer[4096];CHECK(run_file("tests/modules/principal.lume",out)==0);read_output(out,buffer,sizeof(buffer));CHECK(strcmp(buffer,"contador carregado\nmodulo\n<modulo matematica>\n30\n1\n2\n2\n")==0);fclose(out);}
static void test_nested(void){FILE *out=tmpfile();char buffer[512];CHECK(run_file("tests/modules/nested_main.lume",out)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"5\n")!=NULL);fclose(out);}
static void test_aliases_and_cache(void){FILE *out=tmpfile();char buffer[4096];CHECK(run_file("tests/modules/alias.lume",out)==0);read_output(out,buffer,sizeof(buffer));CHECK(strcmp(buffer,"contador carregado\n42\nLume\nPython\nLua\n9\n1\n")==0);fclose(out);}
static void test_errors(void){FILE *out=tmpfile();char buffer[2048];CHECK(run_file("tests/modules/invalid_import.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nivel principal")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/privado.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nao exporta")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/alias_missing.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nao exporta")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/alias_collision.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"ja foi declarado")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/inexistente.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"encontrar o modulo")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/cycle_main.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"circular")!=NULL);fclose(out);}
static void test_repl_and_tools(void){FILE *in=tmpfile(),*out=tmpfile();RuntimeIO io={in,out};char buffer[8192];char *explain[]={"lume","--explicar","tests/modules/alias.lume"};char *analyze[]={"lume","--analisar","tests/modules/alias.lume"};fputs("importe \"tests/modules/nao_existe\" como ausente\nimporte \"tests/modules/matematica\" como mat\nmat.somar(3,4)\n:sair\n",in);rewind(in);CHECK(repl_run(io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"encontrar o modulo")!=NULL);CHECK(strstr(buffer,"7\n")!=NULL);freopen(NULL,"w+",out);io.input=stdin;CHECK(cli_run(3,explain,io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"como \"texto_lib\"")!=NULL);freopen(NULL,"w+",out);CHECK(cli_run(3,analyze,io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"Analisando:")!=NULL);CHECK(strstr(buffer,"nao foi definido")==NULL);fclose(in);fclose(out);}
static bool parses(const char *text){Source source;TokenArray tokens;ErrorList errors;Program *program=NULL;bool ok;source_init(&source);token_array_init(&tokens);error_list_init(&errors);ok=source_from_bytes(&source,"<alias>",text,strlen(text));if(ok)ok=lexer_scan(&source,&tokens,&errors);if(ok)ok=parser_parse_program(&tokens,&program,&errors);program_free(program);error_list_free(&errors);token_array_free(&tokens);source_free(&source);return ok;}
static void test_alias_syntax(void){static const char *const invalid[]={"importe\n","importe \"\n","importe \"lume/texto\" como\n","importe \"lume/texto\" como 1\n","importe \"lume/texto\" como (\n","importe \"lume/texto\" como \"abc\"\n","importe \"lume/texto\" como txt lixo\n"};size_t i;CHECK(parses("variavel como = 1\nescreva(como)\n"));CHECK(parses("importe \"lume/texto\" como txt\n"));for(i=0U;i<sizeof(invalid)/sizeof(invalid[0]);i++)CHECK(!parses(invalid[i]));}
static void test_analyzer_errors(void){FILE *out=tmpfile();RuntimeIO io={stdin,out};char buffer[2048];char *missing[]={"lume","--analisar","tests/modules/inexistente.lume"};char *private_member[]={"lume","--analisar","tests/modules/privado.lume"};char *cycle[]={"lume","--analisar","tests/modules/cycle_main.lume"};CHECK(cli_run(3,missing,io)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"encontrar o modulo")!=NULL);freopen(NULL,"w+",out);CHECK(cli_run(3,private_member,io)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nao exporta")!=NULL);freopen(NULL,"w+",out);CHECK(cli_run(3,cycle,io)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"circular")!=NULL);fclose(out);}
int main(void){test_basic_cache_state_list();test_nested();test_aliases_and_cache();test_errors();test_repl_and_tools();test_analyzer_errors();test_alias_syntax();if(failures==0){puts("Todos os testes de modulos passaram.");return 0;}return 1;}
