#include <stdio.h>
#include <string.h>
#include "cli.h"
#include "repl.h"
static int failures=0;
#define CHECK(c) do{if(!(c)){fprintf(stderr,"FALHA %s:%d: %s\n",__FILE__,__LINE__,#c);failures++;}}while(0)
static size_t read_output(FILE *file,char *buffer,size_t capacity){size_t n;rewind(file);n=fread(buffer,1U,capacity-1U,file);buffer[n]='\0';return n;}
static int run_file(const char *path,FILE *out){RuntimeIO io={stdin,out};char *argv[]={"lume",(char *)path};return cli_run(2,argv,io);}
static void test_basic_cache_state_list(void){FILE *out=tmpfile();char buffer[4096];CHECK(run_file("tests/modules/principal.lume",out)==0);read_output(out,buffer,sizeof(buffer));CHECK(strcmp(buffer,"contador carregado\nmodulo\n<modulo matematica>\n30\n1\n2\n2\n")==0);fclose(out);}
static void test_nested(void){FILE *out=tmpfile();char buffer[512];CHECK(run_file("tests/modules/nested_main.lume",out)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"5\n")!=NULL);fclose(out);}
static void test_errors(void){FILE *out=tmpfile();char buffer[2048];CHECK(run_file("tests/modules/invalid_import.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nivel principal")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/privado.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nao exporta")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/inexistente.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"encontrar o modulo")!=NULL);freopen(NULL,"w+",out);CHECK(run_file("tests/modules/cycle_main.lume",out)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"circular")!=NULL);fclose(out);}
static void test_repl_and_tools(void){FILE *in=tmpfile(),*out=tmpfile();RuntimeIO io={in,out};char buffer[8192];char *explain[]={"lume","--explicar","tests/modules/nested_main.lume"};char *analyze[]={"lume","--analisar","tests/modules/principal.lume"};fputs("importe \"tests/modules/matematica\"\nmatematica.somar(3,4)\n:sair\n",in);rewind(in);CHECK(repl_run(io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"7\n")!=NULL);freopen(NULL,"w+",out);io.input=stdin;CHECK(cli_run(3,explain,io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"5\n")!=NULL);freopen(NULL,"w+",out);CHECK(cli_run(3,analyze,io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"Analisando:")!=NULL);fclose(in);fclose(out);}
static void test_analyzer_errors(void){FILE *out=tmpfile();RuntimeIO io={stdin,out};char buffer[2048];char *missing[]={"lume","--analisar","tests/modules/inexistente.lume"};char *private_member[]={"lume","--analisar","tests/modules/privado.lume"};char *cycle[]={"lume","--analisar","tests/modules/cycle_main.lume"};CHECK(cli_run(3,missing,io)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"encontrar o modulo")!=NULL);freopen(NULL,"w+",out);CHECK(cli_run(3,private_member,io)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"nao exporta")!=NULL);freopen(NULL,"w+",out);CHECK(cli_run(3,cycle,io)==1);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"circular")!=NULL);fclose(out);}
int main(void){test_basic_cache_state_list();test_nested();test_errors();test_repl_and_tools();test_analyzer_errors();if(failures==0){puts("Todos os testes de modulos passaram.");return 0;}return 1;}
