#include <stdio.h>
#include <string.h>
#include "cli.h"
#include "memory.h"
#include "session.h"
#include "project.h"
static int failures=0;
#define CHECK(c) do{if(!(c)){fprintf(stderr,"FALHA %s:%d: %s\n",__FILE__,__LINE__,#c);failures++;}}while(0)
static void output(FILE *f,char *b,size_t n){size_t got;rewind(f);got=fread(b,1U,n-1U,f);b[got]='\0';}
static int run(const char *code,char *shown,size_t cap){RuntimeIO io;LumeSession session;ErrorList errors;Source *source=NULL;FILE *f=tmpfile();bool ok;io.input=stdin;io.output=f;session_init(&session,io);error_list_init(&errors);ok=session_execute(&session,"tests/stdlib_program.lume",code,strlen(code),false,&source,&errors);output(f,shown,cap);if(!ok&&source!=NULL){source_free(source);memory_free(source);}error_list_free(&errors);session_free(&session);fclose(f);return ok?0:1;}
static void math_tests(void){char b[4096];const char *code="importe \"lume/matematica\"\nescreva(matematica.absoluto(-10))\nescreva(matematica.absoluto(-2.5))\nescreva(matematica.minimo(10, 2.5))\nescreva(matematica.maximo(10, 20))\nescreva(matematica.potencia(2, 8))\nescreva(matematica.raiz(81))\nescreva(matematica.piso(2.9))\nescreva(matematica.teto(2.1))\nescreva(matematica.arredonde(2.5))\nescreva(matematica.PI)\nescreva(matematica.E)\nescreva(tipo(matematica))\n";CHECK(run(code,b,sizeof(b))==0);CHECK(strstr(b,"10\n2.5\n2.5\n20\n256\n9\n2\n3\n3")!=NULL);CHECK(strstr(b,"modulo")!=NULL);CHECK(run("importe \"lume/matematica\"\nmatematica.raiz(-1)\n",b,sizeof(b))==1);CHECK(run("importe \"lume/matematica\"\nmatematica.absoluto(inteiro(\"-9223372036854775808\"))\n",b,sizeof(b))==1);}
static void text_tests(void){char b[4096];const char *code="importe \"lume/texto\"\nescreva(texto.maiusculo(\"Lume á\"))\nescreva(texto.minusculo(\"LUME Á\"))\nescreva(texto.contem(\"Lume é legal\", \"legal\"))\nescreva(texto.comeca_com(\"Lume\", \"Lu\"))\nescreva(texto.termina_com(\"arquivo.lume\", \".lume\"))\nescreva(texto.aparar(\" \\tLume \\n\"))\nescreva(texto.subtexto(\"Olá\", 1, 3))\nescreva(texto.substitua(\"a-a-a\", \"a\", \"x\"))\nescreva(texto.separe(\"a,b,c\", \",\"))\nescreva(texto.junte([\"a\", \"b\", \"c\"], \",\"))\nescreva(texto.junte([], \",\"))\n";CHECK(run(code,b,sizeof(b))==0);CHECK(strstr(b,"LUME á")!=NULL);CHECK(strstr(b,"lume Á")!=NULL);CHECK(strstr(b,"verdadeiro\nverdadeiro\nverdadeiro")!=NULL);CHECK(strstr(b,"lá")!=NULL);CHECK(strstr(b,"x-x-x")!=NULL);CHECK(strstr(b,"[\"a\", \"b\", \"c\"]")!=NULL);CHECK(run("importe \"lume/texto\"\ntexto.separe(\"a\", \"\")\n",b,sizeof(b))==1);CHECK(run("importe \"lume/texto\"\ntexto.junte([1], \",\")\n",b,sizeof(b))==1);}
static void file_time_tests(void){char b[4096];const char *code="importe \"lume/arquivo\"\narquivo.escreva(\"stdlib-temp.txt\", \"A\")\narquivo.adicione(\"stdlib-temp.txt\", \"B\")\nescreva(arquivo.existe(\"stdlib-temp.txt\"))\nescreva(arquivo.leia(\"stdlib-temp.txt\"))\narquivo.remova(\"stdlib-temp.txt\")\nescreva(arquivo.existe(\"stdlib-temp.txt\"))\n";CHECK(run(code,b,sizeof(b))==0);CHECK(strstr(b,"verdadeiro\nAB\nfalso")!=NULL);CHECK(run("importe \"lume/tempo\"\nescreva(tempo.agora())\nescreva(tempo.timestamp())\ntempo.durma(1)\n",b,sizeof(b))==0);CHECK(strlen(b)>=21U);}
static void integration_tests(void){RuntimeIO io;char b[4096];FILE *f=tmpfile();char *analyze[]={(char *)"lume",(char *)"--analisar",(char *)"tests/projects/stdlib/src/principal.lume"};char *verify[]={(char *)"lume",(char *)"verificar",(char *)"tests/projects/stdlib"};char *resolve[]={(char *)"lume",(char *)"resolver",(char *)"tests/projects/stdlib"};io.input=stdin;io.output=f;CHECK(cli_run(3,analyze,io)==0);freopen(NULL,"w+",f);CHECK(cli_run(3,verify,io)==0);output(f,b,sizeof(b));CHECK(strstr(b,"\n5\n")==NULL);freopen(NULL,"w+",f);CHECK(cli_run(3,resolve,io)==0);{Source lock;source_init(&lock);CHECK(source_load_file(&lock,"tests/projects/stdlib/lume.lock"));CHECK(strstr(lock.bytes,"dependencia]]")==NULL);source_free(&lock);CHECK(remove("tests/projects/stdlib/lume.lock")==0);}fclose(f);}
static void repl_namespace_tests(void){RuntimeIO io;LumeSession session;ErrorList errors;Source *source=NULL;FILE *f=tmpfile();char b[1024];LumeProject p;io.input=stdin;io.output=f;session_init(&session,io);error_list_init(&errors);CHECK(session_execute(&session,"<repl>","importe \"lume/matematica\"\n",26U,false,&source,&errors));CHECK(session_execute(&session,"<repl>","matematica.raiz(81)\n",20U,true,&source,&errors));output(f,b,sizeof(b));CHECK(strstr(b,"9")!=NULL);error_list_free(&errors);session_free(&session);fclose(f);project_init(&p);CHECK(!project_load(&p,"tests/projects/invalid/reserved_dependency"));CHECK(strstr(p.message,"dependencia")!=NULL);project_free(&p);}
int main(void){math_tests();text_tests();file_time_tests();integration_tests();repl_namespace_tests();if(failures==0){puts("Todos os testes da biblioteca padrao passaram.");return 0;}return 1;}
