#include <stdio.h>
#include <string.h>
#include "cli.h"
#include "education.h"
#include "interpreter.h"
#include "lexer.h"
#include "parser.h"
static int failures=0;
#define CHECK(c) do{if(!(c)){fprintf(stderr,"FALHA %s:%d: %s\n",__FILE__,__LINE__,#c);failures++;}}while(0)
typedef struct{size_t counts[TRACE_LIST_REMOVE+1U];size_t max_depth;}Collector;
static void collect(void *context,const TraceEvent *event){Collector *c=context;c->counts[event->type]++;if(event->call_depth>c->max_depth)c->max_depth=event->call_depth;}
static void test_event_sequence(void){const char *code="funcao fat(n){se n<=1{retorne 1};retorne n*fat(n-1)}\nvariavel xs=[1,2]\nxs[0]=3\nadicione(xs,4)\nvariavel z=xs[0]\nvariavel i=0\nenquanto i<1{i=i+1}\npara j de 1 ate 2{z=z+j}\nse z>0{z=fat(3)}\nremova(xs,0)\n";Source source;TokenArray tokens;ErrorList errors;Program *program=NULL;Environment environment;RuntimeIO io;RuntimeTrace trace;Collector collector={{0U},0U};FILE *out=tmpfile();bool ok;source_init(&source);token_array_init(&tokens);error_list_init(&errors);environment_init(&environment,NULL);io.input=stdin;io.output=out;ok=source_from_bytes(&source,"educacao.lume",code,strlen(code));if(ok)ok=lexer_scan(&source,&tokens,&errors);if(ok)ok=parser_parse_program(&tokens,&program,&errors);trace.callback=collect;trace.context=&collector;trace.stop_requested=false;if(ok)ok=interpreter_execute_program_with_trace(program,&environment,&io,&trace,&errors);CHECK(ok);CHECK(collector.counts[TRACE_PROGRAM_START]==1U);CHECK(collector.counts[TRACE_PROGRAM_END]==1U);CHECK(collector.counts[TRACE_IF_CONDITION]>0U);CHECK(collector.counts[TRACE_WHILE_ITERATION]==1U);CHECK(collector.counts[TRACE_FOR_ITERATION]==2U);CHECK(collector.counts[TRACE_FUNCTION_CALL]==3U);CHECK(collector.max_depth>=3U);CHECK(collector.counts[TRACE_LIST_CREATE]==1U);CHECK(collector.counts[TRACE_INDEX_READ]>0U);CHECK(collector.counts[TRACE_INDEX_WRITE]==1U);CHECK(collector.counts[TRACE_LIST_APPEND]==1U);CHECK(collector.counts[TRACE_LIST_REMOVE]==1U);fclose(out);environment_free(&environment);program_free(program);error_list_free(&errors);token_array_free(&tokens);source_free(&source);}
static size_t read_output(FILE *file,char *buffer,size_t capacity){size_t n;rewind(file);n=fread(buffer,1U,capacity-1U,file);buffer[n]='\0';return n;}
static void test_renderer_and_stepper(void){RuntimeIO io;FILE *in=tmpfile(),*out=tmpfile();char buffer[8192];char *explain[]={"lume","--explicar","exemplos/algoritmo_listas.lume"};char *step[]={"lume","--passo","exemplos/variaveis.lume"};io.input=in;io.output=out;CHECK(cli_run(3,explain,io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"1. Inicio do programa")!=NULL);CHECK(strstr(buffer,"Criou a lista")!=NULL);CHECK(strstr(buffer,"Iteracao")!=NULL);freopen(NULL,"w+",out);fputs("v\np\nq\n",in);rewind(in);CHECK(cli_run(3,step,io)==0);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"Variaveis visiveis")!=NULL);CHECK(strstr(buffer,"Pilha de chamadas")!=NULL);CHECK(strstr(buffer,"encerrada pelo usuario")!=NULL);fclose(in);fclose(out);}
static void test_summary_limit(void){FILE *out=tmpfile();RuntimeIO io={stdin,out};Source source;RuntimeTrace trace;EducationRenderer renderer;TraceEvent event;char buffer[32768];size_t i;source_init(&source);CHECK(source_from_bytes(&source,"x","",0U));trace.callback=education_trace_callback;trace.context=&renderer;trace.stop_requested=false;education_renderer_init(&renderer,&io,&source,&trace,EDUCATION_EXPLAIN);memset(&event,0,sizeof(event));event.type=TRACE_WHILE_ITERATION;for(i=1U;i<=250U;i++){event.iteration=i;education_trace_callback(&renderer,&event);}event.type=TRACE_PROGRAM_END;education_trace_callback(&renderer,&event);read_output(out,buffer,sizeof(buffer));CHECK(strstr(buffer,"eventos intermediarios foram resumidos")!=NULL);source_free(&source);fclose(out);}
int main(void){test_event_sequence();test_renderer_and_stepper();test_summary_limit();if(failures==0){puts("Todos os testes educacionais passaram.");return 0;}return 1;}
