#include <stdio.h>
#include <string.h>
#include "cli.h"
#include "dependency.h"
#include "source.h"
static int failures=0;
#define CHECK(c) do{if(!(c)){fprintf(stderr,"FALHA %s:%d: %s\n",__FILE__,__LINE__,#c);failures++;}}while(0)
static void text(FILE *f,char *b,size_t n){size_t got;rewind(f);got=fread(b,1U,n-1U,f);b[got]='\0';}
static void command(const char *verb,const char *path,int expected,const char *needle){RuntimeIO io;char b[8192];FILE *f=tmpfile();char *args[]={(char *)"lume",(char *)verb,(char *)path};io.input=stdin;io.output=f;CHECK(cli_run(3,args,io)==expected);text(f,b,sizeof(b));CHECK(strstr(b,needle)!=NULL);fclose(f);}
static void test_graph(void){DependencyGraph g;dependency_graph_init(&g);CHECK(dependency_graph_resolve(&g,"tests/dependencies/app"));CHECK(g.count==2U);CHECK(strcmp(g.nodes[1].project.name,"matematica")==0);dependency_graph_free(&g);dependency_graph_init(&g);CHECK(dependency_graph_resolve(&g,"tests/dependencies/transitive_app"));CHECK(g.count==3U);dependency_graph_free(&g);dependency_graph_init(&g);CHECK(!dependency_graph_resolve(&g,"tests/dependencies/wrong_name"));CHECK(strstr(g.message,"aponta para")!=NULL);dependency_graph_free(&g);dependency_graph_init(&g);CHECK(!dependency_graph_resolve(&g,"tests/dependencies/missing"));CHECK(strstr(g.message,"Erro de dependencia")!=NULL);dependency_graph_free(&g);dependency_graph_init(&g);CHECK(!dependency_graph_resolve(&g,"tests/dependencies/cycle_a"));CHECK(strstr(g.message,"cycle_a 1.0.0")!=NULL);CHECK(strstr(g.message,"cycle_b 2.0.0")!=NULL);dependency_graph_free(&g);}
static void test_cli(void){command("executar","tests/dependencies/app",0,"90");command("executar","tests/dependencies/transitive_app",0,"41");command("executar","tests/dependencies/leak",1,"Nao foi possivel encontrar");command("verificar","tests/dependencies/app",0,"Verificando projeto");}
static void test_lock(void){RuntimeIO io;char first[8192],second[8192],shown[8192];Source source;FILE *f=tmpfile();char *args[]={(char *)"lume",(char *)"resolver",(char *)"tests/dependencies/transitive_app"};io.input=stdin;io.output=f;CHECK(cli_run(3,args,io)==0);source_init(&source);CHECK(source_load_file(&source,"tests/dependencies/transitive_app/lume.lock"));strncpy(first,source.bytes,sizeof(first)-1U);first[sizeof(first)-1U]='\0';source_free(&source);freopen(NULL,"w+",f);CHECK(cli_run(3,args,io)==0);source_init(&source);CHECK(source_load_file(&source,"tests/dependencies/transitive_app/lume.lock"));strncpy(second,source.bytes,sizeof(second)-1U);second[sizeof(second)-1U]='\0';CHECK(strcmp(first,second)==0);CHECK(strstr(second,"nome = \"a\"")!=NULL);CHECK(strstr(second,"nome = \"b\"")!=NULL);source_free(&source);{FILE *lock=fopen("tests/dependencies/transitive_app/lume.lock","wb");char *run[]={(char *)"lume",(char *)"executar",(char *)"tests/dependencies/transitive_app"};CHECK(lock!=NULL);if(lock!=NULL){fputs("lock_version = 0\n",lock);fclose(lock);}freopen(NULL,"w+",f);CHECK(cli_run(3,run,io)==0);text(f,shown,sizeof(shown));CHECK(strstr(shown,"desatualizado")!=NULL);}CHECK(remove("tests/dependencies/transitive_app/lume.lock")==0);fclose(f);}
int main(void){test_graph();test_cli();test_lock();if(failures==0){puts("Todos os testes de dependencias passaram.");return 0;}return 1;}
