#include "dependency.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "memory.h"
#include "source.h"
static char *copy_n(const char *s,size_t n){return memory_copy_string(s,n);}
static char *normalize(char *path){size_t read=0U,written=0U,count=0U,length=strlen(path);size_t *starts=memory_reallocate_array(NULL,length+1U,sizeof(*starts));bool rooted=length>0U&&path[0]=='/';if(starts==NULL){memory_free(path);return NULL;}if(rooted)path[written++]='/';while(read<length){size_t start,n;while(read<length&&(path[read]=='/'||path[read]=='\\'))read++;start=read;while(read<length&&path[read]!='/'&&path[read]!='\\')read++;n=read-start;if(n==0U||(n==1U&&path[start]=='.'))continue;if(n==2U&&path[start]=='.'&&path[start+1U]=='.'&&count>0U){written=starts[--count];continue;}starts[count++]=written;if(written>0U&&path[written-1U]!='/')path[written++]='/';memmove(path+written,path+start,n);written+=n;}path[written]='\0';memory_free(starts);return path;}
static char *join(const char *a,const char *b){size_t al=strlen(a),bl=strlen(b),i;char *r=memory_allocate(al+bl+2U);if(r==NULL)return NULL;memcpy(r,a,al);i=al;if(i>0U&&r[i-1U]!='/'&&r[i-1U]!='\\')r[i++]='/';memcpy(r+i,b,bl+1U);return normalize(r);}
void dependency_graph_init(DependencyGraph *g){memset(g,0,sizeof(*g));}
void dependency_graph_free(DependencyGraph *g){size_t i;if(g==NULL)return;for(i=0U;i<g->count;i++)project_free(&g->nodes[i].project);memory_free(g->nodes);dependency_graph_init(g);}
static bool add_node(DependencyGraph *g,const char *path,size_t *index){DependencyNode *grown;size_t cap;if(g->count==g->capacity){if(!memory_grow_capacity(g->capacity,g->count+1U,&cap))return false;grown=memory_reallocate_array(g->nodes,cap,sizeof(*grown));if(grown==NULL)return false;g->nodes=grown;g->capacity=cap;}*index=g->count;project_init(&g->nodes[g->count].project);g->nodes[g->count].state=DEPENDENCY_UNVISITED;g->count++;if(!project_load(&g->nodes[*index].project,path)){snprintf(g->message,sizeof(g->message),"Erro de dependencia: %s",g->nodes[*index].project.message);return false;}return true;}
static size_t find_path(const DependencyGraph *g,const char *path){size_t i;for(i=0U;i<g->count;i++)if(strcmp(g->nodes[i].project.root_path,path)==0)return i;return SIZE_MAX;}
static bool resolve_node(DependencyGraph *g,size_t index,size_t *stack,size_t depth){size_t i;LumeProject *p=&g->nodes[index].project;g->nodes[index].state=DEPENDENCY_VISITING;stack[depth]=index;for(i=0U;i<p->dependency_count;i++){ProjectDependency *d=&p->dependencies[i];size_t target;d->resolved_path=normalize(d->resolved_path);if(d->resolved_path==NULL)return false;target=find_path(g,d->resolved_path);if(target==SIZE_MAX&&!add_node(g,d->resolved_path,&target))return false;p=&g->nodes[index].project;d=&p->dependencies[i];if(strcmp(d->name,g->nodes[target].project.name)!=0){snprintf(g->message,sizeof(g->message),"Erro de dependencia: '%s' aponta para o projeto '%s'.",d->name,g->nodes[target].project.name);return false;}d->version=copy_n(g->nodes[target].project.version,strlen(g->nodes[target].project.version));d->target_index=target;if(d->version==NULL)return false;if(g->nodes[target].state==DEPENDENCY_VISITING){size_t at;size_t used=(size_t)snprintf(g->message,sizeof(g->message),"Erro de dependencia: dependencia circular:\n");for(at=0U;at<=depth;at++)if(stack[at]==target||used>strlen("Erro de dependencia: dependencia circular:\n")){used+=(size_t)snprintf(g->message+used,sizeof(g->message)-used,"%s %s -> ",g->nodes[stack[at]].project.name,g->nodes[stack[at]].project.version);}snprintf(g->message+used,sizeof(g->message)-used,"%s %s",g->nodes[target].project.name,g->nodes[target].project.version);return false;}if(g->nodes[target].state==DEPENDENCY_UNVISITED&&!resolve_node(g,target,stack,depth+1U))return false;}g->nodes[index].state=DEPENDENCY_RESOLVED;return true;}
bool dependency_graph_resolve(DependencyGraph *g,const char *root){size_t index,*stack;dependency_graph_free(g);if(!add_node(g,root,&index))return false;g->root_index=index;stack=memory_reallocate_array(NULL,256U,sizeof(*stack));if(stack==NULL)return false;{bool ok=resolve_node(g,index,stack,0U);memory_free(stack);return ok;}}
const LumeProject *dependency_graph_root(const DependencyGraph *g){return g->count==0U?NULL:&g->nodes[g->root_index].project;}
static bool within(const char *path,const char *root){size_t n=strlen(root);return strncmp(path,root,n)==0&&(path[n]=='/'||path[n]=='\\'||path[n]=='\0');}
static bool unsafe_subpath(const char *s){return strcmp(s,"..")==0||strncmp(s,"../",3U)==0||strstr(s,"/../")!=NULL||strstr(s,"\\..\\")!=NULL;}
static bool readable(const char *path){FILE *f=fopen(path,"rb");if(f==NULL)return false;fclose(f);return true;}
static bool root_candidate(const char *root,const char *requested,size_t length,char **out){char *part=copy_n(requested,length),*candidate;if(part==NULL)return false;candidate=join(root,part);memory_free(part);if(candidate==NULL)return false;if(!(length>=5U&&memcmp(requested+length-5U,".lume",5U)==0)){size_t old=strlen(candidate);char *grown=memory_reallocate_array(candidate,old+6U,1U);if(grown==NULL){memory_free(candidate);return false;}memcpy(grown+old,".lume",6U);candidate=grown;}if(!readable(candidate)){memory_free(candidate);return false;}*out=candidate;return true;}
bool dependency_graph_resolve_import(const DependencyGraph *g,const char *importer,const char *requested,size_t length,char **out){size_t i;const LumeProject *owner=NULL;for(i=0U;i<g->count;i++)if(within(importer,g->nodes[i].project.root_path)){if(owner==NULL||strlen(g->nodes[i].project.root_path)>strlen(owner->root_path))owner=&g->nodes[i].project;}if(owner==NULL)return false;if(root_candidate(owner->source_path,requested,length,out))return true;for(i=0U;i<owner->module_path_count;i++)if(root_candidate(owner->module_paths[i],requested,length,out))return true;for(i=0U;i<owner->dependency_count;i++){ProjectDependency *d=&owner->dependencies[i];size_t n=strlen(d->name);if(length<n||memcmp(requested,d->name,n)!=0||(length>n&&requested[n]!='/'&&requested[n]!='\\'))continue;{const LumeProject *target=&g->nodes[d->target_index].project;if(length==n){*out=copy_n(target->entry_path,strlen(target->entry_path));return *out!=NULL;}else{const char *sub=requested+n+1U;if(unsafe_subpath(sub))return false;*out=join(target->source_path,sub);if(*out!=NULL&&!(length>=5U&&memcmp(requested+length-5U,".lume",5U)==0)){size_t old=strlen(*out);char *grown=memory_reallocate_array(*out,old+6U,1U);if(grown==NULL){memory_free(*out);*out=NULL;return false;}memcpy(grown+old,".lume",6U);*out=grown;}return *out!=NULL;}}}return false;}
static int compare_nodes(const void *a,const void *b){const DependencyNode *const *x=a,*const *y=b;int c=strcmp((*x)->project.name,(*y)->project.name);return c!=0?c:strcmp((*x)->project.root_path,(*y)->project.root_path);}
bool dependency_lock_write(const DependencyGraph *g,char *message,size_t cap){const LumeProject *root=dependency_graph_root(g);DependencyNode **sorted;char *path;FILE *f;size_t i,n=g->count>0U?g->count-1U:0U;path=join(root->root_path,"lume.lock");sorted=memory_reallocate_array(NULL,n,sizeof(*sorted));if(path==NULL||(n>0U&&sorted==NULL)){memory_free(path);memory_free(sorted);return false;}for(i=0U;i<n;i++)sorted[i]=&g->nodes[i+1U];qsort(sorted,n,sizeof(*sorted),compare_nodes);f=fopen(path,"wb");if(f==NULL){snprintf(message,cap,"Erro de dependencia: nao foi possivel gravar lume.lock.");memory_free(path);memory_free(sorted);return false;}fputs("lock_version = 1\n",f);if(n==0U)fputs("dependencias = []\n",f);for(i=0U;i<n;i++)fprintf(f,"\n[[dependencia]]\nnome = \"%s\"\nversao = \"%s\"\ncaminho = \"%s\"\n",sorted[i]->project.name,sorted[i]->project.version,sorted[i]->project.root_path);if(fclose(f)!=0){memory_free(path);memory_free(sorted);return false;}snprintf(message,cap,"%zu dependencia(s) resolvida(s).\nlume.lock atualizado.",n);memory_free(path);memory_free(sorted);return true;}
bool dependency_lock_current(const DependencyGraph *g,bool *exists){const LumeProject *root=dependency_graph_root(g);Source source;char *path;size_t i,count=0U;bool ok=true;path=join(root->root_path,"lume.lock");if(path==NULL)return false;source_init(&source);*exists=source_load_file(&source,path);memory_free(path);if(!*exists)return true;if(strstr(source.bytes,"lock_version = 1")==NULL)ok=false;{const char *at=source.bytes;while((at=strstr(at,"[[dependencia]]"))!=NULL){count++;at+=15U;}}if(count+1U!=g->count)ok=false;for(i=0U;ok&&i<g->count;i++)if(i!=g->root_index){char needle[512];snprintf(needle,sizeof(needle),"nome = \"%s\"",g->nodes[i].project.name);if(strstr(source.bytes,needle)==NULL)ok=false;snprintf(needle,sizeof(needle),"versao = \"%s\"",g->nodes[i].project.version);if(strstr(source.bytes,needle)==NULL)ok=false;snprintf(needle,sizeof(needle),"caminho = \"%s\"",g->nodes[i].project.root_path);if(strstr(source.bytes,needle)==NULL)ok=false;}source_free(&source);return ok;}
