#include "education.h"
#include <string.h>
#include "diagnostic.h"
#include "interpreter.h"
#include "lexer.h"
#include "memory.h"
#include "parser.h"
#include "module.h"
enum { EDUCATION_EVENT_LIMIT = 200 };
static void indent(FILE *out,size_t depth){size_t i,n=depth>16U?16U:depth;for(i=0U;i<n;i++)fputs("  ",out);}
static void print_value(FILE *out,const Value *value){if(value==NULL)fputs("nulo",out);else value_print(out,value);}
static void print_expression(FILE *out,const Source *source,SourceSpan span){size_t start,end;if(source==NULL||span.start.offset>=source->length)return;start=span.start.offset;end=span.end.offset;if(end>source->length)end=source->length;if(end<=start||end-start>100U)return;fputs(" — `",out);fwrite(source->bytes+start,1U,end-start,out);fputc('`',out);}
static void binding_line(void *context,const char *name,size_t length,const Value *value,bool mutable){FILE *out=context;fprintf(out,"    %s %.*s = ",mutable?"variavel":"constante",(int)length,name);print_value(out,value);fputc('\n',out);}
void education_show_variables(FILE *output,const Environment *environment){const Environment *scope=environment;size_t level=0U;fputs("Variaveis visiveis:\n",output);while(scope!=NULL){fprintf(output,"  Escopo %zu%s:\n",level,scope->is_global?" (global)":"");environment_visit_current(scope,binding_line,output);scope=scope->parent;level++;}}
static void show_stack(EducationRenderer *r){size_t i;fputs("Pilha de chamadas:\n",r->io->output);if(r->stack_count==0U)fputs("    <programa principal>\n",r->io->output);for(i=0U;i<r->stack_count;i++)fprintf(r->io->output,"    %zu. %.*s\n",i+1U,(int)r->stack_lengths[i],r->stack_names[i]);}
static void step_prompt(EducationRenderer *r){char command[32];if(r->mode!=EDUCATION_STEP||r->continuing)return;for(;;){fputs("[Enter=proximo, v=variaveis, p=pilha, c=continuar, q=sair] > ",r->io->output);fflush(r->io->output);if(fgets(command,sizeof(command),r->io->input)==NULL){r->trace->stop_requested=true;return;}if(command[0]=='\n'||command[0]=='\r')return;if(command[0]=='v')education_show_variables(r->io->output,r->current_environment);else if(command[0]=='p')show_stack(r);else if(command[0]=='c'){r->continuing=true;return;}else if(command[0]=='q'){r->trace->stop_requested=true;return;}else fputs("Comando invalido. Use Enter, v, p, c ou q.\n",r->io->output);}}
void education_renderer_init(EducationRenderer *r,RuntimeIO *io,const Source *source,RuntimeTrace *trace,EducationMode mode){memset(r,0,sizeof(*r));r->io=io;r->source=source;r->trace=trace;r->mode=mode;}
static bool should_render(EducationRenderer *r,const TraceEvent *e){if(r->mode==EDUCATION_STEP||e->type==TRACE_PROGRAM_END)return true;if(r->rendered<EDUCATION_EVENT_LIMIT)return true;r->omitted++;return false;}
void education_trace_callback(void *context,const TraceEvent *e){EducationRenderer *r=context;FILE *out=r->io->output;bool pop=false;r->current_environment=e->environment;if(e->type==TRACE_FUNCTION_ENTER&&r->stack_count<64U){r->stack_names[r->stack_count]=e->name;r->stack_lengths[r->stack_count++]=e->name_length;}if(e->type==TRACE_FUNCTION_RETURN&&r->stack_count>0U)pop=true;if(!should_render(r,e))return;if(e->type==TRACE_PROGRAM_END&&r->omitted>0U)fprintf(out,"... %zu eventos intermediarios foram resumidos.\n",r->omitted);r->step++;r->rendered++;fprintf(out,"%zu. ",r->step);indent(out,e->call_depth);switch(e->type){
case TRACE_PROGRAM_START:fputs("Inicio do programa.",out);break;case TRACE_PROGRAM_END:fputs("Fim do programa.",out);break;
case TRACE_DECLARE_VARIABLE:case TRACE_DECLARE_CONSTANT:fprintf(out,"Declarou %s '%.*s' com valor ",e->type==TRACE_DECLARE_VARIABLE?"a variavel":"a constante",(int)e->name_length,e->name);print_value(out,e->after);fputc('.',out);break;
case TRACE_DECLARE_FUNCTION:fprintf(out,"Preparou a funcao '%.*s'.",(int)e->name_length,e->name);break;
case TRACE_ASSIGN:fprintf(out,"Atualizou '%.*s': ",(int)e->name_length,e->name);print_value(out,e->before);fputs(" -> ",out);print_value(out,e->after);fputc('.',out);break;
case TRACE_IF_CONDITION:fprintf(out,"A condicao do 'se' deu %s; seguira o ramo %s.",e->decision?"verdadeiro":"falso",e->decision?"principal":"alternativo, se existir");print_expression(out,r->source,e->span);break;
case TRACE_WHILE_CONDITION:fprintf(out,"A condicao de 'enquanto' deu %s.",e->decision?"verdadeiro":"falso");break;case TRACE_WHILE_ITERATION:fprintf(out,"Iniciou a iteracao %zu de 'enquanto'.",e->iteration);break;case TRACE_WHILE_END:fprintf(out,"Terminou 'enquanto' apos %zu iteracao(oes).",e->iteration);break;
case TRACE_FOR_START:fprintf(out,"Iniciou 'para %.*s' no intervalo ",(int)e->name_length,e->name);print_value(out,e->before);fputs(" ate ",out);print_value(out,e->after);fputc('.',out);break;case TRACE_FOR_ITERATION:fprintf(out,"Iteracao %zu de 'para': %.*s = ",e->iteration,(int)e->name_length,e->name);print_value(out,e->after);fputc('.',out);break;case TRACE_FOR_END:fprintf(out,"Terminou 'para' apos %zu iteracao(oes).",e->iteration);break;
case TRACE_FUNCTION_CALL:fprintf(out,"Chamou a funcao '%.*s' com %zu argumento(s).",(int)e->name_length,e->name,e->argument_count);break;case TRACE_FUNCTION_ENTER:fprintf(out,"Entrou em '%.*s' (profundidade %zu).",(int)e->name_length,e->name,e->call_depth);break;case TRACE_FUNCTION_RETURN:fprintf(out,"'%.*s' retornou ",(int)e->name_length,e->name);print_value(out,e->after);fputc('.',out);break;
case TRACE_NATIVE_CALL:fprintf(out,"Chamou a nativa '%.*s'.",(int)e->name_length,e->name);break;case TRACE_OUTPUT:fputs("'escreva' mostrou ",out);print_value(out,e->after);fputc('.',out);break;case TRACE_LIST_CREATE:fputs("Criou a lista ",out);print_value(out,e->after);fputc('.',out);break;case TRACE_INDEX_READ:fprintf(out,"Leu o indice %lld da lista: ",(long long)e->index);print_value(out,e->after);fputc('.',out);break;case TRACE_INDEX_WRITE:fprintf(out,"Alterou o indice %lld: ",(long long)e->index);print_value(out,e->before);fputs(" -> ",out);print_value(out,e->after);fputc('.',out);break;case TRACE_LIST_APPEND:fputs("Adicionou um item; a lista agora e ",out);print_value(out,e->after);fputc('.',out);break;case TRACE_LIST_REMOVE:fprintf(out,"Removeu o indice %lld, obtendo ",(long long)e->index);print_value(out,e->after);fputc('.',out);break;case TRACE_MODULE_IMPORT:fprintf(out,"Importando o modulo '%.*s'.",(int)e->name_length,e->name);break;case TRACE_MODULE_LOADED:fprintf(out,"Modulo '%.*s' carregado.",(int)e->name_length,e->name);break;}
fputc('\n',out);step_prompt(r);if(pop&&r->stack_count>0U)r->stack_count--;}
int education_run_file(const char *path,RuntimeIO io,EducationMode mode){Source source;TokenArray tokens;ErrorList errors;Program *program=NULL;Environment environment;RuntimeTrace trace;EducationRenderer renderer;ModuleRegistry registry;LumeModule current;bool ok;source_init(&source);token_array_init(&tokens);error_list_init(&errors);environment_init(&environment,NULL);ok=source_load_file(&source,path);if(ok)ok=lexer_scan(&source,&tokens,&errors);if(ok)ok=parser_parse_program(&tokens,&program,&errors);trace.callback=education_trace_callback;trace.context=&renderer;trace.stop_requested=false;education_renderer_init(&renderer,&io,&source,&trace,mode);module_registry_init(&registry,&io,&trace);memset(&current,0,sizeof(current));current.path=(char *)path;if(ok)ok=interpreter_execute_program_with_modules(program,&environment,&io,&trace,&registry,&current,&errors);if(!ok&&!trace.stop_requested&&errors.count>0U)diagnostic_render(io.output,registry.error_source==NULL?&source:registry.error_source,&errors.data[0]);if(trace.stop_requested)fputs("Execucao educacional encerrada pelo usuario.\n",io.output);environment_free(&environment);module_registry_free(&registry);program_free(program);error_list_free(&errors);token_array_free(&tokens);source_free(&source);return ok||trace.stop_requested?0:1;}
