#include "list.h"
#include <string.h>
#include "memory.h"
LumeList *list_new(void) { LumeList *list=memory_allocate(sizeof(*list)); if(list!=NULL){list->references=1U;list->items=NULL;list->count=0U;list->capacity=0U;}return list; }
void list_retain(LumeList *list){if(list!=NULL)list->references++;}
void list_release(LumeList *list){size_t i;if(list==NULL)return;if(--list->references!=0U)return;for(i=0U;i<list->count;i++)value_free(&list->items[i]);memory_free(list->items);memory_free(list);}
static bool contains(const LumeList *list,const LumeList *needle){size_t i;if(list==needle)return true;for(i=0U;i<list->count;i++)if(list->items[i].type==VALUE_LIST&&contains(list->items[i].as.list,needle))return true;return false;}
bool list_would_create_cycle(const LumeList *target,const Value *value){return value!=NULL&&value->type==VALUE_LIST&&contains(value->as.list,target);}
bool list_append(LumeList *list,const Value *value){Value *grown,copy=value_null();size_t capacity;if(list==NULL||value==NULL||list_would_create_cycle(list,value))return false;if(list->count==list->capacity){if(!memory_grow_capacity(list->capacity,list->count+1U,&capacity))return false;grown=memory_reallocate_array(list->items,capacity,sizeof(*grown));if(grown==NULL)return false;list->items=grown;list->capacity=capacity;}if(!value_copy(value,&copy))return false;list->items[list->count++]=copy;return true;}
bool list_get(const LumeList *list,size_t index,Value *out){return list!=NULL&&index<list->count&&value_copy(&list->items[index],out);}
bool list_set(LumeList *list,size_t index,const Value *value){Value copy=value_null();if(list==NULL||index>=list->count||value==NULL||list_would_create_cycle(list,value)||!value_copy(value,&copy))return false;value_free(&list->items[index]);list->items[index]=copy;return true;}
bool list_remove(LumeList *list,size_t index,Value *out){if(list==NULL||index>=list->count||out==NULL)return false;*out=list->items[index];if(index+1U<list->count)memmove(&list->items[index],&list->items[index+1U],(list->count-index-1U)*sizeof(*list->items));list->count--;return true;}
static bool append_bytes(char **buffer,size_t *count,size_t *capacity,const char *bytes,size_t length){char *grown;size_t needed,next;if(*count>SIZE_MAX-length-1U)return false;needed=*count+length+1U;if(needed>*capacity){if(!memory_grow_capacity(*capacity,needed,&next))return false;grown=memory_reallocate_array(*buffer,next,sizeof(*grown));if(grown==NULL)return false;*buffer=grown;*capacity=next;}memcpy(*buffer+*count,bytes,length);*count+=length;(*buffer)[*count]='\0';return true;}
bool list_format(const LumeList *list,char **out,size_t *length){char *buffer=NULL,*item;size_t count=0U,capacity=0U,item_length,i;if(!append_bytes(&buffer,&count,&capacity,"[",1U))return false;for(i=0U;i<list->count;i++){if(i>0U&&!append_bytes(&buffer,&count,&capacity,", ",2U))goto error;if(!value_format_nested(&list->items[i],&item,&item_length))goto error;if(!append_bytes(&buffer,&count,&capacity,item,item_length)){memory_free(item);goto error;}memory_free(item);}if(!append_bytes(&buffer,&count,&capacity,"]",1U))goto error;*out=buffer;*length=count;return true;error:memory_free(buffer);return false;}
