#ifndef _WIN32
#define _POSIX_C_SOURCE 200809L
#endif
#include "lume_stdlib.h"
#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <errno.h>
#include <unistd.h>
#endif
#include "callable.h"
#include "list.h"
#include "memory.h"
#include "terminal.h"
static bool err(ErrorList *e,LumeErrorKind k,SourceSpan s,const char *m,const char *h){LumeError x={k,s,m,h,NULL,0U};return error_list_add(e,x)&&false;}
static bool number(const Value *v,double *out){if(v->type==VALUE_INTEGER)*out=(double)v->as.integer;else if(v->type==VALUE_DECIMAL)*out=v->as.decimal;else return false;return true;}
static bool unary_number(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){double x;(void)n;(void)io;(void)c;if(!number(a,&x))return err(e,LUME_ERROR_TYPE,s,"A funcao esperava um numero.","Use um inteiro ou decimal.");*o=value_decimal(x);return true;}
static bool m_abs(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){(void)n;(void)io;(void)c;if(a[0].type==VALUE_INTEGER){if(a[0].as.integer==INT64_MIN)return err(e,LUME_ERROR_NUMERIC,s,"O valor absoluto ultrapassa o limite inteiro.","Converta para decimal antes da operacao.");*o=value_integer(a[0].as.integer<0?-a[0].as.integer:a[0].as.integer);return true;}if(a[0].type==VALUE_DECIMAL){*o=value_decimal(fabs(a[0].as.decimal));return true;}return err(e,LUME_ERROR_TYPE,s,"matematica.absoluto esperava um numero.","Use inteiro ou decimal.");}
static bool m_min(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){double x,y;(void)n;(void)io;(void)c;if(!number(a,&x)||!number(a+1,&y))return err(e,LUME_ERROR_TYPE,s,"minimo esperava dois numeros.","Use inteiros ou decimais.");if(a[0].type==VALUE_INTEGER&&a[1].type==VALUE_INTEGER)*o=value_integer(a[0].as.integer<a[1].as.integer?a[0].as.integer:a[1].as.integer);else *o=value_decimal(x<y?x:y);return true;}
static bool m_max(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){double x,y;(void)n;(void)io;(void)c;if(!number(a,&x)||!number(a+1,&y))return err(e,LUME_ERROR_TYPE,s,"maximo esperava dois numeros.","Use inteiros ou decimais.");if(a[0].type==VALUE_INTEGER&&a[1].type==VALUE_INTEGER)*o=value_integer(a[0].as.integer>a[1].as.integer?a[0].as.integer:a[1].as.integer);else *o=value_decimal(x>y?x:y);return true;}
static bool m_pow(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){double x,y,r;(void)n;(void)io;(void)c;if(!number(a,&x)||!number(a+1,&y))return err(e,LUME_ERROR_TYPE,s,"potencia esperava dois numeros.","Use base e expoente numericos.");r=pow(x,y);if(!isfinite(r))return err(e,LUME_ERROR_NUMERIC,s,"A potencia nao produz um numero representavel.","Use valores menores ou um dominio valido.");*o=value_decimal(r);return true;}
static bool m_sqrt(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){double x;(void)n;(void)io;(void)c;if(!number(a,&x))return err(e,LUME_ERROR_TYPE,s,"matematica.raiz esperava um numero.","Use inteiro ou decimal.");if(x<0.0)return err(e,LUME_ERROR_NUMERIC,s,"Nao existe raiz quadrada real de numero negativo.","Use um numero maior ou igual a zero.");*o=value_decimal(sqrt(x));return true;}
static bool m_floor(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){if(!unary_number(a,n,io,c,o,s,e))return false;o->as.decimal=floor(o->as.decimal);return true;}
static bool m_ceil(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){if(!unary_number(a,n,io,c,o,s,e))return false;o->as.decimal=ceil(o->as.decimal);return true;}
static bool m_round(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){if(!unary_number(a,n,io,c,o,s,e))return false;o->as.decimal=round(o->as.decimal);return true;}
static bool strings2(const Value *a,SourceSpan s,ErrorList *e){return (a[0].type==VALUE_STRING&&a[1].type==VALUE_STRING)||err(e,LUME_ERROR_TYPE,s,"A funcao de texto esperava textos.","Nao ha conversao implicita; use texto(valor). ");}
static bool t_upper(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t i;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"maiusculo esperava texto.","Use um texto.");if(!value_string_copy(a[0].as.string.bytes,a[0].as.string.length,o))return false;for(i=0U;i<o->as.string.length;i++)if((unsigned char)o->as.string.bytes[i]<128U)o->as.string.bytes[i]=(char)toupper((unsigned char)o->as.string.bytes[i]);return true;}
static bool t_lower(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t i;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"minusculo esperava texto.","Use um texto.");if(!value_string_copy(a[0].as.string.bytes,a[0].as.string.length,o))return false;for(i=0U;i<o->as.string.length;i++)if((unsigned char)o->as.string.bytes[i]<128U)o->as.string.bytes[i]=(char)tolower((unsigned char)o->as.string.bytes[i]);return true;}
static bool contains_bytes(const LumeString *x,const LumeString *y){size_t i;if(y->length==0U)return true;if(y->length>x->length)return false;for(i=0U;i<=x->length-y->length;i++)if(memcmp(x->bytes+i,y->bytes,y->length)==0)return true;return false;}
static bool t_contains(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){(void)n;(void)io;(void)c;if(!strings2(a,s,e))return false;*o=value_boolean(contains_bytes(&a[0].as.string,&a[1].as.string));return true;}
static bool t_starts(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){(void)n;(void)io;(void)c;if(!strings2(a,s,e))return false;*o=value_boolean(a[1].as.string.length<=a[0].as.string.length&&memcmp(a[0].as.string.bytes,a[1].as.string.bytes,a[1].as.string.length)==0);return true;}
static bool t_ends(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t x,y;(void)n;(void)io;(void)c;if(!strings2(a,s,e))return false;x=a[0].as.string.length;y=a[1].as.string.length;*o=value_boolean(y<=x&&memcmp(a[0].as.string.bytes+x-y,a[1].as.string.bytes,y)==0);return true;}
static bool t_trim(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t b=0U,z;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"aparar esperava texto.","Use um texto.");z=a[0].as.string.length;while(b<z&&strchr(" \t\r\n\f\v",a[0].as.string.bytes[b])!=NULL)b++;while(z>b&&strchr(" \t\r\n\f\v",a[0].as.string.bytes[z-1U])!=NULL)z--;return value_string_copy(a[0].as.string.bytes+b,z-b,o);}
static size_t next_utf8(const char *b,size_t n,size_t at){unsigned char c=(unsigned char)b[at];size_t step=c<0x80U?1U:c<0xE0U?2U:c<0xF0U?3U:4U;return step<=n-at?at+step:n;}
static bool t_sub(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t at=0U,p=0U,start,end;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_STRING||a[1].type!=VALUE_INTEGER||a[2].type!=VALUE_INTEGER||a[1].as.integer<0||a[2].as.integer<a[1].as.integer)return err(e,LUME_ERROR_INDEX,s,"subtexto exige texto, inicio e fim validos.","Indices usam pontos de codigo e o fim e exclusivo.");start=(size_t)a[1].as.integer;end=(size_t)a[2].as.integer;while(p<start&&at<a[0].as.string.length){at=next_utf8(a[0].as.string.bytes,a[0].as.string.length,at);p++;}{size_t begin=at;while(p<end&&at<a[0].as.string.length){at=next_utf8(a[0].as.string.bytes,a[0].as.string.length,at);p++;}if(p<end)return err(e,LUME_ERROR_INDEX,s,"O fim de subtexto ultrapassa o tamanho.","Use indices entre zero e tamanho(texto).");return value_string_copy(a[0].as.string.bytes+begin,at-begin,o);}}
static bool t_replace(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t i=0U,count=0U,cap=0U;char *buf=NULL;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_STRING||a[1].type!=VALUE_STRING||a[2].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"substitua esperava tres textos.","Informe texto, busca e substituicao.");if(a[1].as.string.length==0U)return err(e,LUME_ERROR_RUNTIME,s,"A busca de substitua nao pode ser vazia.","Use um trecho nao vazio.");while(i<a[0].as.string.length){const char *part;size_t add;if(i+a[1].as.string.length<=a[0].as.string.length&&memcmp(a[0].as.string.bytes+i,a[1].as.string.bytes,a[1].as.string.length)==0){part=a[2].as.string.bytes;add=a[2].as.string.length;i+=a[1].as.string.length;}else{part=a[0].as.string.bytes+i;add=1U;i++;}if(count>SIZE_MAX-add-1U){memory_free(buf);return false;}if(count+add+1U>cap){size_t nc;char *g;if(!memory_grow_capacity(cap,count+add+1U,&nc)){memory_free(buf);return false;}g=memory_reallocate_array(buf,nc,1U);if(g==NULL){memory_free(buf);return false;}buf=g;cap=nc;}memcpy(buf+count,part,add);count+=add;}if(!value_string_copy(buf,count,o)){memory_free(buf);return false;}memory_free(buf);return true;}
static bool t_split(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){LumeList *list;size_t start=0U,i;(void)n;(void)io;(void)c;if(!strings2(a,s,e))return false;if(a[1].as.string.length==0U)return err(e,LUME_ERROR_RUNTIME,s,"O separador nao pode ser vazio.","Use um separador com ao menos um byte.");list=list_new();if(list==NULL)return false;for(i=0U;i+a[1].as.string.length<=a[0].as.string.length;){if(memcmp(a[0].as.string.bytes+i,a[1].as.string.bytes,a[1].as.string.length)==0){Value v=value_null();if(!value_string_copy(a[0].as.string.bytes+start,i-start,&v)||!list_append(list,&v)){value_free(&v);list_release(list);return false;}value_free(&v);i+=a[1].as.string.length;start=i;}else i++;}{Value v=value_null();if(!value_string_copy(a[0].as.string.bytes+start,a[0].as.string.length-start,&v)||!list_append(list,&v)){value_free(&v);list_release(list);return false;}value_free(&v);}*o=value_list(list);return true;}
static bool t_join(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t i,total=0U,at=0U;char *buf;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_LIST||a[1].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"junte esperava uma lista e um separador textual.","Todos os itens da lista devem ser textos.");for(i=0U;i<a[0].as.list->count;i++){if(a[0].as.list->items[i].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"junte encontrou item que nao e texto.","Converta cada item explicitamente.");if(total>SIZE_MAX-a[0].as.list->items[i].as.string.length)return false;total+=a[0].as.list->items[i].as.string.length;if(i>0U){if(total>SIZE_MAX-a[1].as.string.length)return false;total+=a[1].as.string.length;}}buf=memory_allocate(total+1U);if(buf==NULL)return false;for(i=0U;i<a[0].as.list->count;i++){if(i>0U){memcpy(buf+at,a[1].as.string.bytes,a[1].as.string.length);at+=a[1].as.string.length;}memcpy(buf+at,a[0].as.list->items[i].as.string.bytes,a[0].as.list->items[i].as.string.length);at+=a[0].as.list->items[i].as.string.length;}buf[total]='\0';o->type=VALUE_STRING;o->as.string.bytes=buf;o->as.string.length=total;return true;}
static char *file_path(void *context,const Value *v){const char *base=context;size_t bl=strlen(base),pl=v->as.string.length;char *p=memory_allocate(bl+pl+2U);if(p==NULL)return NULL;memcpy(p,base,bl);if(bl>0U&&base[bl-1U]!='/'&&base[bl-1U]!='\\')p[bl++]='/';memcpy(p+bl,v->as.string.bytes,pl);p[bl+pl]='\0';return p;}
static bool file_arg(const Value *a,SourceSpan s,ErrorList *e){return a[0].type==VALUE_STRING||err(e,LUME_ERROR_TYPE,s,"A operacao de arquivo esperava um caminho textual.","Use um caminho em texto.");}
static bool f_exists(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){char *p;FILE *f;(void)n;(void)io;if(!file_arg(a,s,e))return false;p=file_path(c,a);if(p==NULL)return false;f=fopen(p,"rb");*o=value_boolean(f!=NULL);if(f!=NULL)fclose(f);memory_free(p);return true;}
static bool f_read(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){char *p;Source src;(void)n;(void)io;if(!file_arg(a,s,e))return false;p=file_path(c,a);if(p==NULL)return false;source_init(&src);if(!source_load_file(&src,p)){memory_free(p);return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel ler o arquivo.","Confira o caminho e as permissoes.");}memory_free(p);o->type=VALUE_STRING;o->as.string.bytes=src.bytes;o->as.string.length=src.length;memory_free(src.name);return true;}
static bool file_write_mode(const Value *a,void *c,Value *o,SourceSpan s,ErrorList *e,const char *mode){char *p;FILE *f;if(a[0].type!=VALUE_STRING||a[1].type!=VALUE_STRING)return err(e,LUME_ERROR_TYPE,s,"A escrita exige caminho e conteudo textuais.","Use arquivo.escreva(caminho, texto).");p=file_path(c,a);if(p==NULL)return false;f=fopen(p,mode);if(f==NULL){memory_free(p);return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel abrir o arquivo para escrita.","Confira o caminho e as permissoes.");}if(fwrite(a[1].as.string.bytes,1U,a[1].as.string.length,f)!=a[1].as.string.length||fclose(f)!=0){memory_free(p);return err(e,LUME_ERROR_RUNTIME,s,"Falha ao gravar o arquivo.","Confira o espaco e as permissoes.");}memory_free(p);*o=value_null();return true;}
static bool f_write(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){(void)n;(void)io;return file_write_mode(a,c,o,s,e,"wb");}
static bool f_append(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){(void)n;(void)io;return file_write_mode(a,c,o,s,e,"ab");}
static bool f_remove(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){char *p;(void)n;(void)io;if(!file_arg(a,s,e))return false;p=file_path(c,a);if(p==NULL)return false;if(remove(p)!=0){memory_free(p);return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel remover o arquivo.","Confira se existe e se ha permissao.");}memory_free(p);*o=value_null();return true;}
static bool tm_timestamp(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){time_t now;(void)a;(void)n;(void)io;(void)c;(void)s;(void)e;now=time(NULL);if(now==(time_t)-1)return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel consultar o relogio.","Tente novamente.");*o=value_integer((int64_t)now);return true;}
static bool tm_now(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){time_t now;struct tm local;char buf[20];(void)a;(void)n;(void)io;(void)c;now=time(NULL);if(now==(time_t)-1)return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel consultar o relogio.","Tente novamente.");
#ifdef _WIN32
if(localtime_s(&local,&now)!=0){
#else
if(localtime_r(&now,&local)==NULL){
#endif
return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel obter a hora local.","Tente novamente.");}if(strftime(buf,sizeof(buf),"%Y-%m-%d %H:%M:%S",&local)!=19U)return false;return value_string_copy(buf,19U,o);}
static bool tm_sleep(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){int64_t ms;(void)n;(void)io;(void)c;if(a[0].type!=VALUE_INTEGER||a[0].as.integer<0)return err(e,LUME_ERROR_TYPE,s,"durma esperava milissegundos inteiros nao negativos.","Use um inteiro pequeno.");ms=a[0].as.integer;if(ms>86400000)return err(e,LUME_ERROR_NUMERIC,s,"O intervalo de durma e grande demais.","Use no maximo 86400000 ms.");
#ifdef _WIN32
Sleep((DWORD)ms);
#else
{struct timespec req;req.tv_sec=(time_t)(ms/1000);req.tv_nsec=(long)((ms%1000)*1000000);while(nanosleep(&req,&req)!=0&&errno==EINTR){}}
#endif
*o=value_null();return true;}
typedef struct {uint64_t state;} RandomContext;
typedef struct {FILE *output;bool cursor_hidden;} TerminalContext;
static uint64_t random_next(RandomContext *c){uint64_t x=c->state;if(x==0U)x=(uint64_t)time(NULL)^UINT64_C(0x9e3779b97f4a7c15);x^=x>>12;x^=x<<25;x^=x>>27;c->state=x;return x*UINT64_C(2685821657736338717);}
static bool random_integer(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){int64_t minimum,maximum,result;uint64_t low,high,width,threshold,value,ordered;(void)n;(void)io;if(a[0].type!=VALUE_INTEGER||a[1].type!=VALUE_INTEGER)return err(e,LUME_ERROR_TYPE,s,"aleatorio.inteiro esperava dois inteiros.","Use aleatorio.inteiro(minimo, maximo).");minimum=a[0].as.integer;maximum=a[1].as.integer;if(minimum>maximum)return err(e,LUME_ERROR_NUMERIC,s,"O minimo nao pode ser maior que o maximo.","Inverta os limites informados.");low=minimum<0?(uint64_t)(minimum-INT64_MIN):UINT64_C(0x8000000000000000)+(uint64_t)minimum;high=maximum<0?(uint64_t)(maximum-INT64_MIN):UINT64_C(0x8000000000000000)+(uint64_t)maximum;width=high-low+UINT64_C(1);if(width==0U)ordered=random_next(c);else{threshold=(UINT64_C(0)-width)%width;do{value=random_next(c);}while(value<threshold);ordered=low+(value%width);}result=ordered<UINT64_C(0x8000000000000000)?INT64_MIN+(int64_t)ordered:(int64_t)(ordered-UINT64_C(0x8000000000000000));*o=value_integer(result);return true;}
static bool random_decimal(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){uint64_t value;(void)a;(void)n;(void)io;(void)s;(void)e;value=random_next(c)>>11;*o=value_decimal((double)value/9007199254740992.0);return true;}
static bool random_choice(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){uint64_t index;(void)n;(void)io;if(a[0].type!=VALUE_LIST)return err(e,LUME_ERROR_TYPE,s,"aleatorio.escolha esperava uma lista.","Use aleatorio.escolha(lista).");if(a[0].as.list->count==0U)return err(e,LUME_ERROR_RUNTIME,s,"Nao e possivel escolher um item de uma lista vazia.","Adicione ao menos um item antes da escolha.");index=random_next(c)%(uint64_t)a[0].as.list->count;return list_get(a[0].as.list,(size_t)index,o);}
static bool terminal_noargs(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e,bool (*action)(FILE *)){(void)a;(void)n;(void)c;if(!action(io->output))return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel escrever no terminal.","Confira se a saida esta disponivel.");*o=value_null();return true;}
static bool term_clear(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){return terminal_noargs(a,n,io,c,o,s,e,terminal_clear);}
static bool term_hide(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){TerminalContext *context=c;(void)a;(void)n;if(!terminal_cursor(io->output,false))return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel ocultar o cursor.","Confira se o terminal aceita sequencias ANSI.");context->output=io->output;context->cursor_hidden=true;*o=value_null();return true;}
static bool term_show(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){TerminalContext *context=c;(void)a;(void)n;if(!terminal_cursor(io->output,true))return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel mostrar o cursor.","Confira se o terminal aceita sequencias ANSI.");context->output=io->output;context->cursor_hidden=false;*o=value_null();return true;}
static bool term_position(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){(void)n;(void)c;if(a[0].type!=VALUE_INTEGER||a[1].type!=VALUE_INTEGER||a[0].as.integer<1||a[1].as.integer<1)return err(e,LUME_ERROR_TYPE,s,"terminal.posicione esperava coluna e linha inteiras positivas.","As coordenadas comecam em 1.");if(!terminal_position(io->output,(size_t)a[0].as.integer,(size_t)a[1].as.integer))return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel posicionar o cursor.","Confira se o terminal aceita sequencias ANSI.");*o=value_null();return true;}
static bool term_size(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){size_t columns,rows;LumeList *list;Value value;(void)a;(void)n;(void)c;(void)s;(void)e;terminal_size(io->output,&columns,&rows);list=list_new();if(list==NULL)return false;value=value_integer((int64_t)columns);if(!list_append(list,&value)){list_release(list);return false;}value=value_integer((int64_t)rows);if(!list_append(list,&value)){list_release(list);return false;}*o=value_list(list);return true;}
static bool term_key_common(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e,bool blocking){int character;bool available;(void)a;(void)n;(void)c;if(!terminal_read_key(io->input,blocking,&character,&available))return err(e,LUME_ERROR_RUNTIME,s,"Nao foi possivel ler uma tecla.","Use um terminal interativo compativel.");if(!available){*o=value_null();return true;}if(character<0||character>255)return err(e,LUME_ERROR_RUNTIME,s,"A tecla lida nao pode ser representada.","Use uma tecla de texto simples.");{char byte=(char)character;return value_string_copy(&byte,1U,o);}}
static bool term_read_key(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){return term_key_common(a,n,io,c,o,s,e,true);}
static bool term_key(const Value *a,size_t n,RuntimeIO *io,void *c,Value *o,SourceSpan s,ErrorList *e){return term_key_common(a,n,io,c,o,s,e,false);}
typedef struct {const char *name;size_t arity;NativeFunction fn;} NativeDef;
static const NativeDef math_defs[]={{"absoluto",1U,m_abs},{"minimo",2U,m_min},{"maximo",2U,m_max},{"potencia",2U,m_pow},{"raiz",1U,m_sqrt},{"piso",1U,m_floor},{"teto",1U,m_ceil},{"arredonde",1U,m_round}};
static const NativeDef text_defs[]={{"maiusculo",1U,t_upper},{"minusculo",1U,t_lower},{"contem",2U,t_contains},{"comeca_com",2U,t_starts},{"termina_com",2U,t_ends},{"aparar",1U,t_trim},{"subtexto",3U,t_sub},{"substitua",3U,t_replace},{"separe",2U,t_split},{"junte",2U,t_join}};
static const NativeDef file_defs[]={{"existe",1U,f_exists},{"leia",1U,f_read},{"escreva",2U,f_write},{"adicione",2U,f_append},{"remova",1U,f_remove}};
static const NativeDef time_defs[]={{"agora",0U,tm_now},{"timestamp",0U,tm_timestamp},{"durma",1U,tm_sleep}};
static const NativeDef random_defs[]={{"inteiro",2U,random_integer},{"decimal",0U,random_decimal},{"escolha",1U,random_choice}};
static const NativeDef terminal_defs[]={{"limpe",0U,term_clear},{"posicione",2U,term_position},{"oculte_cursor",0U,term_hide},{"mostre_cursor",0U,term_show},{"tamanho",0U,term_size},{"leia_tecla",0U,term_read_key},{"tecla",0U,term_key}};
bool stdlib_is_path(const char *p,size_t n){return n>5U&&memcmp(p,"lume/",5U)==0;}
static const NativeDef *defs(const char *p,size_t n,size_t *count,bool *math){*math=false;if(n==15U&&memcmp(p,"lume/matematica",15U)==0){*count=sizeof(math_defs)/sizeof(math_defs[0]);*math=true;return math_defs;}if(n==10U&&memcmp(p,"lume/texto",10U)==0){*count=sizeof(text_defs)/sizeof(text_defs[0]);return text_defs;}if(n==12U&&memcmp(p,"lume/arquivo",12U)==0){*count=sizeof(file_defs)/sizeof(file_defs[0]);return file_defs;}if(n==10U&&memcmp(p,"lume/tempo",10U)==0){*count=sizeof(time_defs)/sizeof(time_defs[0]);return time_defs;}if(n==14U&&memcmp(p,"lume/aleatorio",14U)==0){*count=sizeof(random_defs)/sizeof(random_defs[0]);return random_defs;}if(n==13U&&memcmp(p,"lume/terminal",13U)==0){*count=sizeof(terminal_defs)/sizeof(terminal_defs[0]);return terminal_defs;}*count=0U;return NULL;}
bool stdlib_has_export(const char *p,size_t n,const char *name,size_t len){size_t i,count;bool math;const NativeDef *d=defs(p,n,&count,&math);if(d==NULL)return false;if(math&&((len==2U&&memcmp(name,"PI",2U)==0)||(len==1U&&name[0]=='E')))return true;for(i=0U;i<count;i++)if(strlen(d[i].name)==len&&memcmp(d[i].name,name,len)==0)return true;return false;}
static char *base_dir(ModuleRegistry *r,const char *importer){const char *source=importer;size_t n,capacity;char *result;if(r->project_source_path!=NULL)source=r->project_source_path;n=strlen(source);while(n>0U&&source[n-1U]!='/'&&source[n-1U]!='\\')n--;if(r->project_source_path!=NULL&&n>0U)n--;capacity=n+1U;if(capacity<sizeof(RandomContext))capacity=sizeof(RandomContext);result=memory_allocate(capacity);if(result==NULL)return NULL;memset(result,0,capacity);memcpy(result,source,n);result[n]='\0';return result;}
static void *module_context(ModuleRegistry *r,const char *importer,const char *path,size_t length){if(length==14U&&memcmp(path,"lume/aleatorio",14U)==0){RandomContext *context=memory_allocate(sizeof(*context));if(context==NULL)return NULL;context->state=(uint64_t)time(NULL)^((uint64_t)clock()<<32)^((uint64_t)(uintptr_t)context);if(context->state==0U)context->state=UINT64_C(0x9e3779b97f4a7c15);return context;}if(length==13U&&memcmp(path,"lume/terminal",13U)==0){TerminalContext *context=memory_allocate(sizeof(*context));if(context!=NULL){context->output=NULL;context->cursor_hidden=false;}return context;}return base_dir(r,importer);}
void stdlib_free_context(const char *path,void *context){if(path!=NULL&&strcmp(path,"lume/terminal")==0&&context!=NULL){TerminalContext *terminal=context;if(terminal->cursor_hidden&&terminal->output!=NULL)(void)terminal_cursor(terminal->output,true);}memory_free(context);}
bool stdlib_create_module(ModuleRegistry *r,const char *importer,const char *p,size_t n,LumeModule **out,ErrorList *errors,SourceSpan span){size_t i,count,extra=0U;bool math;const NativeDef *d=defs(p,n,&count,&math);LumeModule *m;if(d==NULL)return err(errors,LUME_ERROR_MODULE,span,"Modulo da biblioteca padrao desconhecido.","Use um modulo oficial documentado, como lume/matematica ou lume/terminal.");m=memory_allocate(sizeof(*m));if(m==NULL)return false;memset(m,0,sizeof(*m));m->path=memory_copy_string(p,n);m->name=memory_copy_string(p+5U,n-5U);source_init(&m->source);environment_init(&m->environment,NULL);m->state=MODULE_LOADED;m->native_context=module_context(r,importer,p,n);extra=math?2U:0U;m->exports=memory_reallocate_array(NULL,count+extra,sizeof(*m->exports));m->export_lengths=memory_reallocate_array(NULL,count+extra,sizeof(*m->export_lengths));if(m->path==NULL||m->name==NULL||m->native_context==NULL||m->exports==NULL||m->export_lengths==NULL)return false;for(i=0U;i<count;i++){Callable *callable=callable_new_custom(d[i].name,d[i].arity,d[i].fn,m->native_context);Value v=value_callable(callable);m->exports[m->export_count]=memory_copy_string(d[i].name,strlen(d[i].name));m->export_lengths[m->export_count++]=strlen(d[i].name);if(callable==NULL||m->exports[m->export_count-1U]==NULL||!environment_define_native(&m->environment,d[i].name,strlen(d[i].name),&v,span,errors)){value_free(&v);return false;}value_free(&v);}if(math){Value pi=value_decimal(3.14159265358979323846),ev=value_decimal(2.71828182845904523536);const char *names[]={"PI","E"};Value vals[]={pi,ev};for(i=0U;i<2U;i++){m->exports[m->export_count]=memory_copy_string(names[i],strlen(names[i]));m->export_lengths[m->export_count++]=strlen(names[i]);if(!environment_define_native(&m->environment,names[i],strlen(names[i]),&vals[i],span,errors))return false;}}*out=m;return true;}
