#include "module.h"
#include <string.h>
#include "interpreter.h"
#include "dependency.h"
#include "lexer.h"
#include "memory.h"
#include "parser.h"
#include "lume_stdlib.h"
static bool module_error(ErrorList *errors,SourceSpan span,const char *message,const char *subject,size_t length){LumeError error;error.kind=LUME_ERROR_MODULE;error.span=span;error.message=message;error.suggestion="Confira o caminho, os exports e as dependencias do modulo.";error.subject=subject;error.subject_length=length;return error_list_add(errors,error)&&false;}
static bool has_extension(const char *path,size_t length){return length>=5U&&memcmp(path+length-5U,".lume",5U)==0;}
static bool normalize_path(const char *importer,const char *requested,size_t requested_length,char **out){size_t importer_length=strlen(importer),directory=importer_length,i,total,segment_count=0U;char *joined,*normalized;size_t *segments;bool absolute=requested_length>0U&&(requested[0]=='/'||requested[0]=='\\'||(requested_length>2U&&requested[1]==':'));while(directory>0U&&importer[directory-1U]!='/'&&importer[directory-1U]!='\\')directory--;total=(absolute?0U:directory)+requested_length+(has_extension(requested,requested_length)?0U:5U);joined=memory_allocate(total+1U);segments=memory_reallocate_array(NULL,total+1U,sizeof(*segments));normalized=memory_allocate(total+2U);if(joined==NULL||segments==NULL||normalized==NULL){memory_free(joined);memory_free(segments);memory_free(normalized);return false;}i=0U;if(!absolute&&directory>0U){memcpy(joined,importer,directory);i=directory;}memcpy(joined+i,requested,requested_length);i+=requested_length;if(!has_extension(requested,requested_length)){memcpy(joined+i,".lume",5U);i+=5U;}joined[i]='\0';{size_t at=0U,written=0U;bool rooted=i>0U&&(joined[0]=='/'||joined[0]=='\\');if(rooted)normalized[written++]='/';while(at<i){size_t start,length;while(at<i&&(joined[at]=='/'||joined[at]=='\\'))at++;start=at;while(at<i&&joined[at]!='/'&&joined[at]!='\\')at++;length=at-start;if(length==0U||(length==1U&&joined[start]=='.'))continue;if(length==2U&&joined[start]=='.'&&joined[start+1U]=='.'){if(segment_count>0U)written=segments[--segment_count];else if(!rooted){segments[segment_count++]=written;if(written>0U)normalized[written++]='/';memcpy(normalized+written,"..",2U);written+=2U;}continue;}segments[segment_count++]=written;if(written>0U&&normalized[written-1U]!='/')normalized[written++]='/';memcpy(normalized+written,joined+start,length);written+=length;}normalized[written]='\0';}memory_free(joined);memory_free(segments);*out=normalized;return true;}
static bool readable(const char *path){FILE *f=fopen(path,"rb");if(f==NULL)return false;fclose(f);return true;}
static bool from_root(const char *root,const char *requested,size_t length,char **out){size_t n=strlen(root);char *fake=memory_allocate(n+8U);bool ok;if(fake==NULL)return false;memcpy(fake,root,n);memcpy(fake+n,"/_root_",8U);ok=normalize_path(fake,requested,length,out);memory_free(fake);return ok;}
static bool resolve_path(ModuleRegistry *r,const char *importer,const char *requested,size_t length,char **out){size_t i;char *candidate;if(!normalize_path(importer,requested,length,&candidate))return false;if(readable(candidate)||r->project_source_path==NULL){*out=candidate;return true;}memory_free(candidate);if(r->dependency_graph!=NULL){if(dependency_graph_resolve_import(r->dependency_graph,importer,requested,length,&candidate)){*out=candidate;return true;}return normalize_path(importer,requested,length,out);}if(!from_root(r->project_source_path,requested,length,&candidate))return false;if(readable(candidate)){*out=candidate;return true;}memory_free(candidate);for(i=0U;i<r->project_module_path_count;i++){if(!from_root(r->project_module_paths[i],requested,length,&candidate))return false;if(readable(candidate)){*out=candidate;return true;}memory_free(candidate);}return normalize_path(importer,requested,length,out);}
static const char *base_name(const char *path){const char *name=path,*at;for(at=path;*at!='\0';at++)if(*at=='/'||*at=='\\')name=at+1;return name;}
static LumeModule *find_module(ModuleRegistry *r,const char *path){size_t i;for(i=0U;i<r->count;i++)if(strcmp(r->modules[i]->path,path)==0)return r->modules[i];return NULL;}
static bool register_module(ModuleRegistry *r,LumeModule *module){LumeModule **grown;size_t capacity;if(r->count==r->capacity){if(!memory_grow_capacity(r->capacity,r->count+1U,&capacity))return false;grown=memory_reallocate_array(r->modules,capacity,sizeof(*grown));if(grown==NULL)return false;r->modules=grown;r->capacity=capacity;}r->modules[r->count++]=module;return true;}
static bool standard_module(ModuleRegistry *r,const char *importer,const Stmt *s,LumeModule **out,ErrorList *errors){char *key=memory_copy_string(s->as.import.path,s->as.import.path_length);LumeModule *m;if(key==NULL)return false;m=find_module(r,key);memory_free(key);if(m!=NULL){*out=m;return true;}if(!stdlib_create_module(r,importer,s->as.import.path,s->as.import.path_length,&m,errors,s->span))return false;if(!register_module(r,m))return false;*out=m;return true;}
void module_registry_init(ModuleRegistry *r,RuntimeIO *io,RuntimeTrace *trace){r->modules=NULL;r->count=0U;r->capacity=0U;r->io=io;r->trace=trace;r->error_source=NULL;r->project_source_path=NULL;r->project_module_paths=NULL;r->project_module_path_count=0U;r->dependency_graph=NULL;}
void module_registry_set_project(ModuleRegistry *r,const char *source_path,char *const *paths,size_t count){r->project_source_path=source_path;r->project_module_paths=paths;r->project_module_path_count=count;}
void module_registry_set_dependencies(ModuleRegistry *r,const struct DependencyGraph *graph){r->dependency_graph=graph;}
static void module_free(LumeModule *m){size_t i;if(m==NULL)return;environment_free(&m->environment);for(i=0U;i<m->export_count;i++)memory_free(m->exports[i]);memory_free(m->exports);memory_free(m->export_lengths);program_free(m->program);source_free(&m->source);memory_free(m->native_context);memory_free(m->path);memory_free(m->name);memory_free(m);}
void module_registry_free(ModuleRegistry *r){size_t i;if(r==NULL)return;for(i=0U;i<r->count;i++)module_free(r->modules[i]);memory_free(r->modules);r->modules=NULL;r->count=0U;r->capacity=0U;}
static bool collect_exports(LumeModule *m){size_t i,count=0U;for(i=0U;i<m->program->statements.count;i++)if(m->program->statements.data[i]->exported)count++;if(count==0U)return true;m->exports=memory_reallocate_array(NULL,count,sizeof(*m->exports));m->export_lengths=memory_reallocate_array(NULL,count,sizeof(*m->export_lengths));if(m->exports==NULL||m->export_lengths==NULL)return false;for(i=0U;i<m->program->statements.count;i++){const Stmt *s=m->program->statements.data[i];const char *name=NULL;size_t length=0U;if(!s->exported)continue;if(s->type==STMT_FUNCTION){name=s->as.function.name;length=s->as.function.name_length;}else{name=s->as.declaration.name;length=s->as.declaration.name_length;}m->exports[m->export_count]=memory_copy_string(name,length);if(m->exports[m->export_count]==NULL)return false;m->export_lengths[m->export_count++]=length;}return true;}
bool module_registry_import(ModuleRegistry *r,const char *importer,const Stmt *statement,LumeModule **out,ErrorList *errors){char *path;LumeModule *m;TokenArray tokens;bool ok;if(stdlib_is_path(statement->as.import.path,statement->as.import.path_length))return standard_module(r,importer,statement,out,errors);if(!resolve_path(r,importer,statement->as.import.path,statement->as.import.path_length,&path))return false;m=find_module(r,path);if(m!=NULL){memory_free(path);if(m->state==MODULE_LOADING)return module_error(errors,statement->span,"Import circular detectado.",m->path,strlen(m->path));if(m->state==MODULE_FAILED)return module_error(errors,statement->span,"Este modulo falhou em uma tentativa anterior.",m->path,strlen(m->path));*out=m;return true;}m=memory_allocate(sizeof(*m));if(m==NULL){memory_free(path);return false;}memset(m,0,sizeof(*m));m->path=path;{const char *base=base_name(path);size_t length=strlen(base);if(length>=5U)length-=5U;m->name=memory_copy_string(base,length);}source_init(&m->source);environment_init(&m->environment,NULL);m->state=MODULE_LOADING;if(m->name==NULL||!register_module(r,m)){module_free(m);return false;}token_array_init(&tokens);ok=source_load_file(&m->source,path);if(!ok){m->state=MODULE_FAILED;return module_error(errors,statement->as.import.path_span,"Nao foi possivel encontrar o modulo importado.",path,strlen(path));}r->error_source=&m->source;ok=lexer_scan(&m->source,&tokens,errors);if(ok)ok=parser_parse_program(&tokens,&m->program,errors);token_array_free(&tokens);if(ok)ok=interpreter_execute_program_with_modules(m->program,&m->environment,r->io,r->trace,r,m,errors);if(ok)ok=collect_exports(m);m->state=ok?MODULE_LOADED:MODULE_FAILED;if(!ok)return false;*out=m;return true;}
bool module_get_export(LumeModule *m,const char *name,size_t length,Value *out,SourceSpan span,ErrorList *errors){size_t i;for(i=0U;i<m->export_count;i++)if(m->export_lengths[i]==length&&memcmp(m->exports[i],name,length)==0)return environment_get(&m->environment,name,length,out,span,errors);return module_error(errors,span,"O modulo nao exporta o membro solicitado.",name,length);}
static bool has_export(const LumeModule *m,const char *name,size_t length){size_t i;for(i=0U;i<m->export_count;i++)if(m->export_lengths[i]==length&&memcmp(m->exports[i],name,length)==0)return true;return false;}
static LumeModule *module_for_binding(LumeModule **imports,const Stmt **statements,size_t count,const char *name,size_t length){size_t i;for(i=0U;i<count;i++)if(statements[i]->as.import.binding_length==length&&memcmp(statements[i]->as.import.binding,name,length)==0)return imports[i];return NULL;}
static bool validate_expr(ModuleRegistry *,const Source *,const Expr *,LumeModule **,const Stmt **,size_t,ErrorList *);
static bool validate_stmt(ModuleRegistry *r,const Source *source,const Stmt *s,LumeModule **imports,const Stmt **import_statements,size_t import_count,ErrorList *errors){size_t i;switch(s->type){case STMT_EXPRESSION:return validate_expr(r,source,s->as.expression.expression,imports,import_statements,import_count,errors);case STMT_VARIABLE_DECLARATION:case STMT_CONSTANT_DECLARATION:return validate_expr(r,source,s->as.declaration.initializer,imports,import_statements,import_count,errors);case STMT_ASSIGNMENT:return validate_expr(r,source,s->as.assignment.value,imports,import_statements,import_count,errors);case STMT_BLOCK:for(i=0U;i<s->as.block.statements.count;i++)if(!validate_stmt(r,source,s->as.block.statements.data[i],imports,import_statements,import_count,errors))return false;return true;case STMT_IF:return validate_expr(r,source,s->as.if_statement.condition,imports,import_statements,import_count,errors)&&validate_stmt(r,source,s->as.if_statement.then_branch,imports,import_statements,import_count,errors)&&(s->as.if_statement.else_branch==NULL||validate_stmt(r,source,s->as.if_statement.else_branch,imports,import_statements,import_count,errors));case STMT_WHILE:return validate_expr(r,source,s->as.while_statement.condition,imports,import_statements,import_count,errors)&&validate_stmt(r,source,s->as.while_statement.body,imports,import_statements,import_count,errors);case STMT_FOR:return validate_expr(r,source,s->as.for_statement.start,imports,import_statements,import_count,errors)&&validate_expr(r,source,s->as.for_statement.end,imports,import_statements,import_count,errors)&&validate_stmt(r,source,s->as.for_statement.body,imports,import_statements,import_count,errors);case STMT_FUNCTION:return validate_stmt(r,source,s->as.function.body,imports,import_statements,import_count,errors);case STMT_RETURN:return s->as.return_statement.value==NULL||validate_expr(r,source,s->as.return_statement.value,imports,import_statements,import_count,errors);case STMT_INDEX_ASSIGNMENT:return validate_expr(r,source,s->as.index_assignment.target,imports,import_statements,import_count,errors)&&validate_expr(r,source,s->as.index_assignment.index,imports,import_statements,import_count,errors)&&validate_expr(r,source,s->as.index_assignment.value,imports,import_statements,import_count,errors);case STMT_IMPORT:return true;}return true;}
static bool validate_expr(ModuleRegistry *r,const Source *source,const Expr *e,LumeModule **imports,const Stmt **statements,size_t count,ErrorList *errors){size_t i;(void)r;(void)source;if(e==NULL)return true;switch(e->type){case EXPR_LITERAL:case EXPR_IDENTIFIER:return true;case EXPR_UNARY:return validate_expr(r,source,e->as.unary.operand,imports,statements,count,errors);case EXPR_BINARY:return validate_expr(r,source,e->as.binary.left,imports,statements,count,errors)&&validate_expr(r,source,e->as.binary.right,imports,statements,count,errors);case EXPR_GROUPING:return validate_expr(r,source,e->as.grouping.expression,imports,statements,count,errors);case EXPR_CALL:if(!validate_expr(r,source,e->as.call.callee,imports,statements,count,errors))return false;for(i=0U;i<e->as.call.argument_count;i++)if(!validate_expr(r,source,e->as.call.arguments[i],imports,statements,count,errors))return false;return true;case EXPR_LIST:for(i=0U;i<e->as.list.count;i++)if(!validate_expr(r,source,e->as.list.elements[i],imports,statements,count,errors))return false;return true;case EXPR_INDEX:return validate_expr(r,source,e->as.index.target,imports,statements,count,errors)&&validate_expr(r,source,e->as.index.index,imports,statements,count,errors);case EXPR_MEMBER:if(e->as.member.target->type==EXPR_IDENTIFIER){LumeModule *m=module_for_binding(imports,statements,count,e->as.member.target->as.identifier.name,e->as.member.target->as.identifier.length);if(m!=NULL&&!has_export(m,e->as.member.name,e->as.member.name_length))return module_error(errors,e->as.member.name_span,"O modulo nao exporta o membro solicitado.",e->as.member.name,e->as.member.name_length);}return validate_expr(r,source,e->as.member.target,imports,statements,count,errors);}return true;}
bool module_registry_validate_program(ModuleRegistry *r,const char *importer,const Source *source,const Program *program,ErrorList *errors){size_t i,count=0U;LumeModule **imports=NULL;const Stmt **statements=NULL;bool ok=true;r->error_source=source;for(i=0U;i<program->statements.count;i++)if(program->statements.data[i]->type==STMT_IMPORT)count++;if(count>0U){imports=memory_reallocate_array(NULL,count,sizeof(*imports));statements=memory_reallocate_array(NULL,count,sizeof(*statements));if(imports==NULL||statements==NULL){memory_free(imports);memory_free(statements);return false;}}count=0U;for(i=0U;i<program->statements.count;i++){const Stmt *s=program->statements.data[i];char *path;LumeModule *m;TokenArray tokens;if(s->type!=STMT_IMPORT)continue;if(stdlib_is_path(s->as.import.path,s->as.import.path_length)){if(!standard_module(r,importer,s,&m,errors)){ok=false;break;}imports[count]=m;statements[count]=s;count++;continue;}if(!resolve_path(r,importer,s->as.import.path,s->as.import.path_length,&path)){ok=false;break;}m=find_module(r,path);if(m!=NULL){memory_free(path);if(m->state==MODULE_LOADING){ok=module_error(errors,s->span,"Import circular detectado.",m->path,strlen(m->path));break;}if(m->state==MODULE_FAILED){ok=false;break;}}else{m=memory_allocate(sizeof(*m));if(m==NULL){memory_free(path);ok=false;break;}memset(m,0,sizeof(*m));m->path=path;{const char *base=base_name(path);size_t length=strlen(base);if(length>=5U)length-=5U;m->name=memory_copy_string(base,length);}source_init(&m->source);environment_init(&m->environment,NULL);m->state=MODULE_LOADING;if(m->name==NULL||!register_module(r,m)){module_free(m);ok=false;break;}token_array_init(&tokens);if(!source_load_file(&m->source,path)){m->state=MODULE_FAILED;ok=module_error(errors,s->as.import.path_span,"Nao foi possivel encontrar o modulo importado.",path,strlen(path));token_array_free(&tokens);break;}r->error_source=&m->source;ok=lexer_scan(&m->source,&tokens,errors);if(ok)ok=parser_parse_program(&tokens,&m->program,errors);token_array_free(&tokens);if(ok)ok=collect_exports(m);if(ok)ok=module_registry_validate_program(r,m->path,&m->source,m->program,errors);m->state=ok?MODULE_LOADED:MODULE_FAILED;if(!ok)break;}imports[count]=m;statements[count]=s;count++;}if(ok){r->error_source=source;for(i=0U;i<program->statements.count;i++)if(!validate_stmt(r,source,program->statements.data[i],imports,statements,count,errors)){ok=false;break;}}memory_free(imports);memory_free(statements);return ok;}
